In [1]:
project_name = "Fake News Detection"         # project setup
python_version = "3.12"

print("Project:", project_name)
print("Python Version:", python_version)
print("Setup successful!")

Project: Fake News Detection
Python Version: 3.12
Setup successful!

In [2]:
news = [
    "Government announces a new education policy",
    "Scientists discover a new planet",
    "Celebrity turns into an alien overnight"
]

labels = ["REAL", "REAL", "FAKE"]

print("Total news records:", len(news))
print("Total labels:", len(labels))

print("\nFirst news:", news[0])
print("First label:", labels[0])          # practice

Total news records: 3
Total labels: 3

First news: Government announces a new education policy
First label: REAL

In [3]:
import pandas as pd                     # importing pandas

data = {
    "news": [
        "Government announces a new education policy",
        "Scientists discover a new planet",
        "Celebrity turns into an alien overnight"
    ],
    "label": ["REAL", "REAL", "FAKE"]
}

df = pd.DataFrame(data)

df

                                          news label
0  Government announces a new education policy  REAL
1             Scientists discover a new planet  REAL
2      Celebrity turns into an alien overnight  FAKE

In [4]:
df.head()     # output first rows

                                          news label
0  Government announces a new education policy  REAL
1             Scientists discover a new planet  REAL
2      Celebrity turns into an alien overnight  FAKE

In [5]:
print("Dataset shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset shape: (3, 2)
Number of rows: 3
Number of columns: 2

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   news    3 non-null      str
 1   label   3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [7]:
import pandas as pd                # practice dataset

data = {
    "news": [
        "Government announces a new education policy",
        "Scientists discover a new planet",
        "Scientists discover a new planet",
        None
    ],
    "label": ["REAL", "REAL", "REAL", "FAKE"]
}

df = pd.DataFrame(data)

df

                                          news label
0  Government announces a new education policy  REAL
1             Scientists discover a new planet  REAL
2             Scientists discover a new planet  REAL
3                                          NaN  FAKE

In [8]:
df.isnull().sum()          # for missing values

news     1
label    0
dtype: int64

In [9]:
df.duplicated().sum()            # for duplicate values

np.int64(1)

In [10]:
df = df.dropna(subset=["news"])          # data cleaning
df = df.drop_duplicates()

df = df.reset_index(drop=True)

df

                                          news label
0  Government announces a new education policy  REAL
1             Scientists discover a new planet  REAL

In [11]:
print("Missing values:")                     # cleaning verification
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())
print("Final shape:", df.shape)

Missing values:
news     0
label    0
dtype: int64

Duplicate rows: 0
Final shape: (2, 2)

In [12]:
print(df["label"].value_counts())        # counting real and fake news

label
REAL    2
Name: count, dtype: int64

In [13]:
print("Total records:", len(df))
print("\nClass distribution:")
print(df["label"].value_counts())

print("\nClass percentages:")
print((df["label"].value_counts(normalize=True) * 100).round(2))

Total records: 2

Class distribution:
label
REAL    2
Name: count, dtype: int64

Class percentages:
label
REAL    100.0
Name: proportion, dtype: float64

In [14]:
from pathlib import Path     # checking files of dataset in notebook

data_folder = Path("../data")

print("Fake.csv exists:", (data_folder / "Fake.csv").exists())
print("True.csv exists:", (data_folder / "True.csv").exists())

Fake.csv exists: False
True.csv exists: False

In [15]:
from pathlib import Path        # checking current folder

print("Current working directory:")
print(Path.cwd())

print("\nFiles and folders here:")
print(list(Path.cwd().iterdir()))

Current working directory:
D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection

Files and folders here:
[WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/.ipynb_checkpoints'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/.venv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/data'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/docs'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/Fake_News_Detection.ipynb'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/models'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/notebooks'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/src')]

In [16]:
from pathlib import Path       # checking data folder

project_folder = Path.cwd().parent
data_folder = project_folder / "data"

print("Project folder:", project_folder)
print("Data folder exists:", data_folder.exists())

if data_folder.exists():
    print("Files inside data folder:")
    print(list(data_folder.iterdir()))

Project folder: D:\My Work\ML & AI\Python_Learning\Python_AI_ML
Data folder exists: False

In [17]:
from pathlib import Path

cwd = Path.cwd()

print("Current location:", cwd)
print("Current folder exists:", cwd.exists())
print("Parent folder:", cwd.parent)
print("Parent folders:", list(cwd.parent.iterdir()))

Current location: D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection
Current folder exists: True
Parent folder: D:\My Work\ML & AI\Python_Learning\Python_AI_ML
Parent folders: [WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/.git'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/.ipynb_checkpoints'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/.venv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/01_Python_Revision.ipynb'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/cleaned_iris.csv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/iris.csv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/uncertainty_ml_project')]

In [18]:
from pathlib import Path

project_folder = Path.cwd()
data_folder = project_folder / "data"

print("Project folder:", project_folder)
print("Data folder exists:", data_folder.exists())

if data_folder.exists():
    print("Files inside data:", list(data_folder.iterdir()))

Project folder: D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection
Data folder exists: True
Files inside data: [WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/data/Fake.csv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/data/True.csv')]

In [19]:
from pathlib import Path             # checking csv files inside folder

data_folder = Path.cwd() / "data"

print("Files found:")
print(list(data_folder.iterdir()))

Files found:
[WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/data/Fake.csv'), WindowsPath('D:/My Work/ML & AI/Python_Learning/Python_AI_ML/Fake-News-Detection/data/True.csv')]

In [20]:
import pandas as pd              # loading dataset
from pathlib import Path

# Data folder ka path
data_folder = Path.cwd() / "data"

# Dono CSV files read karna
fake_df = pd.read_csv(data_folder / "Fake.csv")
true_df = pd.read_csv(data_folder / "True.csv")

# Dataset ka size check karna
print("Fake dataset shape:", fake_df.shape)
print("Real dataset shape:", true_df.shape)

# Pehli 5 rows dekhna
display(fake_df.head())
display(true_df.head())

Fake dataset shape: (23481, 4)
Real dataset shape: (21417, 4)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [21]:
print("Fake News Columns:")              # Dataset ko samajhna aur inspect karna & checking columns and missing values
print(fake_df.columns.tolist())

print("\nReal News Columns:")
print(true_df.columns.tolist())

print("\nFake News Missing Values:")
print(fake_df.isnull().sum())

print("\nReal News Missing Values:")
print(true_df.isnull().sum())

Fake News Columns:
['title', 'text', 'subject', 'date']

Real News Columns:
['title', 'text', 'subject', 'date']

Fake News Missing Values:
title      0
text       0
subject    0
date       0
dtype: int64

Real News Missing Values:
title      0
text       0
subject    0
date       0
dtype: int64

In [22]:
# Fake news ko label dena               combining fake and real news
fake_df["label"] = "FAKE"

# Real news ko label dena
true_df["label"] = "REAL"

# Dono datasets ko combine karna
df = pd.concat([fake_df, true_df], ignore_index=True)

# Results check karna
print("Combined dataset shape:", df.shape)
print("\nLabel distribution:")
print(df["label"].value_counts())

display(df.head())

Combined dataset shape: (44898, 5)

Label distribution:
label
FAKE    23481
REAL    21417
Name: count, dtype: int64

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",FAKE
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",FAKE
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",FAKE
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",FAKE
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",FAKE

In [23]:
# Total duplicate rows count karo       checking duplicate records
print("Duplicate rows:", df.duplicated().sum())

# News text ke andar duplicate records check karo
print("Duplicate news texts:", df["text"].duplicated().sum())

Duplicate rows: 209
Duplicate news texts: 6252

In [24]:
# Har news text ke saath kitne different labels hain?        checking the duplicate labels
label_counts = df.groupby("text")["label"].nunique()

# Aise news texts count karo jin ke labels different hain
conflicting_texts = label_counts[label_counts > 1]

print("News texts with conflicting labels:", len(conflicting_texts))

News texts with conflicting labels: 1

In [25]:
# inspecting the conflicting news
# Conflicting news text ki list
conflict_texts = conflicting_texts.index

# Un texts ki tamam rows dekho
conflict_rows = df[df["text"].isin(conflict_texts)]

display(conflict_rows[["title", "text", "label"]])

                                                   title text label
10923  TAKE OUR POLL: Who Do You Think President Trum...       FAKE
11041  Joe Scarborough BERATES Mika Brzezinski Over “...       FAKE
11190  WATCH TUCKER CARLSON Scorch Sanctuary City May...       FAKE
11225  MAYOR OF SANCTUARY CITY: Trump Trying To Make ...       FAKE
11236  SHOCKER: Public School Turns Computer Lab Into...       FAKE
...                                                  ...  ...   ...
21826  FULL VIDEO: THE BLOCKBUSTER INVESTIGATION INTO...       FAKE
21827  (VIDEO) HILLARY CLINTON: RELIGIOUS BELIEFS MUS...       FAKE
21857  (VIDEO)ICE PROTECTING OBAMA: WON’T RELEASE NAM...       FAKE
21873  (VIDEO) HYSTERICAL SNL TAKE ON HILLARY’S ANNOU...       FAKE
32451                     Graphic: Supreme Court roundup       REAL

[627 rows x 3 columns]

In [26]:
print("Number of conflicting texts:", len(conflicting_texts))  # identifying exact confflicting text

for text in conflicting_texts:
    rows = df[df["text"] == text]

    print("\nLabels for this text:")
    print(rows["label"].value_counts())

    display(rows[["title", "label"]])

Number of conflicting texts: 1

Labels for this text:
Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [title, label]
Index: []

In [27]:
# inspecting value of conflict
print("Conflicting text value:")
print(repr(conflicting_texts[0]))

print("\nIs it missing?")
print(pd.isna(conflicting_texts[0]))

print("\nMissing values in text column:")
print(df["text"].isna().sum())

Conflicting text value:

KeyError: 0

In [28]:
print("Conflicting texts count:", len(conflicting_texts))

if len(conflicting_texts) > 0:
    conflict_value = conflicting_texts.index[0]

    print("Conflicting text:")
    print(repr(conflict_value))

    print("\nIs it missing?")
    print(pd.isna(conflict_value))

Conflicting texts count: 1
Conflicting text:
' '

Is it missing?
False

In [29]:
# Empty ya sirf spaces wali news check karo
# Sirf spaces ya empty text wali rows identify karo
blank_text_mask = df["text"].str.strip().eq("")

print("Blank/whitespace-only news rows:", blank_text_mask.sum())

# In rows ke labels dekho
display(df.loc[blank_text_mask, ["title", "text", "label"]])

Blank/whitespace-only news rows: 631

                                                   title text label
10923  TAKE OUR POLL: Who Do You Think President Trum...       FAKE
11041  Joe Scarborough BERATES Mika Brzezinski Over “...       FAKE
11190  WATCH TUCKER CARLSON Scorch Sanctuary City May...       FAKE
11225  MAYOR OF SANCTUARY CITY: Trump Trying To Make ...       FAKE
11236  SHOCKER: Public School Turns Computer Lab Into...       FAKE
...                                                  ...  ...   ...
21826  FULL VIDEO: THE BLOCKBUSTER INVESTIGATION INTO...       FAKE
21827  (VIDEO) HILLARY CLINTON: RELIGIOUS BELIEFS MUS...       FAKE
21857  (VIDEO)ICE PROTECTING OBAMA: WON’T RELEASE NAM...       FAKE
21873  (VIDEO) HYSTERICAL SNL TAKE ON HILLARY’S ANNOU...       FAKE
32451                     Graphic: Supreme Court roundup       REAL

[631 rows x 3 columns]

In [30]:
# removing blank text
# Original dataset ko safe rakhte hue copy banao
df_clean = df.copy()

# Blank ya sirf spaces wali news identify karo
blank_text_mask = (
    df_clean["text"].isna()
    | df_clean["text"].str.strip().eq("")
)

# Blank text wali rows remove karo
df_clean = df_clean.loc[~blank_text_mask].copy()

# Index dobara arrange karo
df_clean = df_clean.reset_index(drop=True)

print("Original dataset rows:", len(df))
print("Cleaned dataset rows:", len(df_clean))
print("Remaining blank texts:", 
      (df_clean["text"].isna() | df_clean["text"].str.strip().eq("")).sum())

Original dataset rows: 44898
Cleaned dataset rows: 44267
Remaining blank texts: 0

In [31]:
# checking duplicate records and remove them
print("Duplicate complete rows:", df_clean.duplicated().sum())

print(
    "Duplicate news texts:",
    df_clean["text"].duplicated().sum()
)

Duplicate complete rows: 209
Duplicate news texts: 5623

In [32]:
# Same news text ki repeated rows remove karo
df_clean = df_clean.drop_duplicates(
    subset=["text"],
    keep="first"
).copy()

# Index reset karo
df_clean = df_clean.reset_index(drop=True)

print("Rows after removing duplicate texts:", len(df_clean))
print("Remaining duplicate texts:", df_clean["text"].duplicated().sum())

Rows after removing duplicate texts: 38644
Remaining duplicate texts: 0

In [33]:
# verifying cleaned dataset
print("Final dataset shape:", df_clean.shape)

print("\nNews labels distribution:")
print(df_clean["label"].value_counts())

print("\nMissing values:")
print(df_clean[["text", "label"]].isnull().sum())

print("\nDuplicate news texts:")
print(df_clean["text"].duplicated().sum())

display(df_clean[["title", "text", "label"]].head())

Final dataset shape: (38644, 5)

News labels distribution:
label
REAL    21191
FAKE    17453
Name: count, dtype: int64

Missing values:
text     0
label    0
dtype: int64

Duplicate news texts:
0

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,FAKE
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,FAKE
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",FAKE
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",FAKE
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,FAKE

In [34]:
print("Available columns:")
print(df_clean.columns.tolist())

print("\nExample news title:")
print(df_clean["title"].iloc[0])

print("\nFirst 300 characters of news text:")
print(df_clean["text"].iloc[0][:300])

print("\nExample label:")
print(df_clean["label"].iloc[0])

Available columns:
['title', 'text', 'subject', 'date', 'label']

Example news title:
 Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing

First 300 characters of news text:
Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger a

Example label:
FAKE

In [35]:
# now preparing x input and y output
# Input features: news article ka text
X = df_clean["text"]

# Target labels: FAKE ya REAL
y = df_clean["label"]

print("Total input articles:", len(X))
print("Total output labels:", len(y))

print("\nFirst input example:")
print(X.iloc[0][:200])

print("\nFirst output label:")
print(y.iloc[0])

Total input articles: 38644
Total output labels: 38644

First input example:
Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former rea

First output label:
FAKE

In [36]:
from sklearn.model_selection import train_test_split

# Dataset ko 80% training aur 20% testing mein divide karna
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training articles:", len(X_train))
print("Testing articles:", len(X_test))
print("Training labels:", len(y_train))
print("Testing labels:", len(y_test))

Training articles: 30915
Testing articles: 7729
Training labels: 30915
Testing labels: 7729

In [37]:
# implementing TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# TF-IDF vectorizer create karna
tfidf = TfidfVectorizer(
    stop_words="english",
    max_df=0.7
)

# Training text se vocabulary aur TF-IDF values seekhna
X_train_tfidf = tfidf.fit_transform(X_train)

# Testing text ko usi vocabulary se transform karna
X_test_tfidf = tfidf.transform(X_test)

print("Training matrix shape:", X_train_tfidf.shape)
print("Testing matrix shape:", X_test_tfidf.shape)
print("Vocabulary size:", len(tfidf.vocabulary_))

Training matrix shape: (30915, 108659)
Testing matrix shape: (7729, 108659)
Vocabulary size: 108659

In [38]:
# training logistic regression model
from sklearn.linear_model import LogisticRegression

# Model create karna
model = LogisticRegression(max_iter=1000)

# Training data se model ko sikhana
model.fit(X_train_tfidf, y_train)

print("Model training completed!")

Model training completed!

In [39]:
# checking model accuracy
from sklearn.metrics import accuracy_score

# Testing data par predictions
y_pred = model.predict(X_test_tfidf)

# Actual aur predicted labels compare karna
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

Model Accuracy: 98.28 %

In [40]:
# Confusion Matrix, Precision, Recall aur F1-score
from sklearn.metrics import (
    confusion_matrix,
    classification_report
)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=["FAKE", "REAL"])

print("Confusion Matrix:")
print(cm)

# Precision, Recall, F1-score
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[3390  101]
 [  32 4206]]

Classification Report:
              precision    recall  f1-score   support

        FAKE       0.99      0.97      0.98      3491
        REAL       0.98      0.99      0.98      4238

    accuracy                           0.98      7729
   macro avg       0.98      0.98      0.98      7729
weighted avg       0.98      0.98      0.98      7729

In [41]:
# Ab custom news prediction test karte hain
# Apni taraf se ek sample news
sample_news = [
    "The government announced a new education policy today."
]

# Trained TF-IDF vectorizer se text convert karo
sample_tfidf = tfidf.transform(sample_news)

# Model se prediction lo
prediction = model.predict(sample_tfidf)

print("News:", sample_news[0])
print("Predicted label:", prediction[0])

News: The government announced a new education policy today.
Predicted label: FAKE

In [42]:
# Saving model
import joblib
from pathlib import Path

# Models ke liye folder banao
models_folder = Path.cwd() / "models"
models_folder.mkdir(exist_ok=True)

# Trained model aur vectorizer save karo
joblib.dump(model, models_folder / "fake_news_model.pkl")
joblib.dump(tfidf, models_folder / "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")
print("Saved in:", models_folder)

Model and vectorizer saved successfully!
Saved in: D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection\models

In [43]:
# making requirements .txt file
packages = """pandas
scikit-learn
joblib
"""

requirements_path = Path.cwd() / "requirements.txt"
requirements_path.write_text(packages, encoding="utf-8")

print("requirements.txt created!")
print(requirements_path)

requirements.txt created!
D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection\requirements.txt

In [44]:
# creating readme
readme_content = """# Fake News Detection using Machine Learning

## Overview
This project uses Natural Language Processing (NLP) and Machine
Learning to classify news articles as FAKE or REAL.

## Technologies Used
- Python
- Pandas
- Scikit-learn
- TF-IDF Vectorization
- Logistic Regression
- Jupyter Notebook

## Project Workflow
1. Load the Fake and Real news datasets.
2. Combine both datasets and assign labels.
3. Remove blank news text and duplicate articles.
4. Split the dataset into training and testing sets.
5. Convert text into numerical features using TF-IDF.
6. Train a Logistic Regression classifier.
7. Evaluate the model using accuracy, precision, recall,
   F1-score, and a confusion matrix.

## Dataset
Fake and Real News Dataset from Kaggle:
https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset

## Model Performance
- Test Accuracy: 98.28%
- Algorithm: Logistic Regression
- Text Features: TF-IDF

Note: Results apply to this dataset and test split.
They do not guarantee reliable detection of all real-world
misinformation.

## How to Run
1. Install dependencies:
   pip install -r requirements.txt

2. Open the Jupyter Notebook.
3. Run the notebook cells in order.

## Saved Model
The trained model and TF-IDF vectorizer are saved in the
models/ directory.

## Disclaimer
This model is an educational project. Its predictions should
not be treated as definitive verification of news.
"""

readme_path = Path.cwd() / "README.md"
readme_path.write_text(readme_content, encoding="utf-8")

print("README.md created successfully!")
print(readme_path)

README.md created successfully!
D:\My Work\ML & AI\Python_Learning\Python_AI_ML\Fake-News-Detection\README.md

In [45]:
# Saved model test karo
import joblib
from pathlib import Path

# Saved files ka folder
models_folder = Path.cwd() / "models"

# Model aur TF-IDF vectorizer dobara load karo
loaded_model = joblib.load(models_folder / "fake_news_model.pkl")
loaded_tfidf = joblib.load(models_folder / "tfidf_vectorizer.pkl")

# Ek sample news par prediction
sample_news = [
    "The government announced a new education policy today."
]

sample_features = loaded_tfidf.transform(sample_news)
prediction = loaded_model.predict(sample_features)

print("Prediction:", prediction[0])
print("Saved model loaded and tested successfully!")

Prediction: FAKE
Saved model loaded and tested successfully!

In [46]:
# Training aur testing data ka overlap check karna
# Training texts ko set mein convert karna
train_texts = set(X_train)

# Testing texts ko set mein convert karna
test_texts = set(X_test)

# Dono sets mein common news texts find karna
overlap_texts = train_texts.intersection(test_texts)

# Result display karna
print("Unique training texts:", len(train_texts))
print("Unique testing texts:", len(test_texts))
print("Overlapping news texts:", len(overlap_texts))

Unique training texts: 30915
Unique testing texts: 7729
Overlapping news texts: 0

In [47]:
# Duplicate-label audit
# Original dataset mein se blank text wali rows remove karna
df_nonblank = df.loc[
    df["text"].notna() & df["text"].str.strip().ne("")
].copy()

# Har exact text ke different labels count karna
label_counts_raw = df_nonblank.groupby("text")["label"].nunique()

# Sirf un texts ko select karna jin ke labels ek se zyada hain
conflicting_raw = label_counts_raw[label_counts_raw > 1]

# Result show karna
print("Nonblank conflicting news texts:", len(conflicting_raw))

Nonblank conflicting news texts: 0

In [48]:
# Duplicate removal verify karna
# Clean dataset mein duplicate text count karna
remaining_duplicates = df_clean["text"].duplicated().sum()

# Result print karna
print("Remaining duplicate texts:", remaining_duplicates)

Remaining duplicate texts: 0

In [49]:
# Class balance check
# Har class mein news articles ki tadaad
print(df_clean["label"].value_counts())

# Har class ka percentage
print(df_clean["label"].value_counts(normalize=True).mul(100).round(2))

label
REAL    21191
FAKE    17453
Name: count, dtype: int64
label
REAL    54.84
FAKE    45.16
Name: proportion, dtype: float64

In [50]:
# Train aur test class distribution compare karna
# Training set mein labels ka percentage
print("Training set:")
print(y_train.value_counts(normalize=True).mul(100).round(2))

# Testing set mein labels ka percentage
print("\nTesting set:")
print(y_test.value_counts(normalize=True).mul(100).round(2))

Training set:
label
REAL    54.84
FAKE    45.16
Name: proportion, dtype: float64

Testing set:
label
REAL    54.83
FAKE    45.17
Name: proportion, dtype: float64

In [51]:
# TF-IDF mein data leakage check
# verification check
print("Training matrix shape:", X_train_tfidf.shape)
print("Testing matrix shape:", X_test_tfidf.shape)
print("Vocabulary size:", len(tfidf.vocabulary_))

Training matrix shape: (30915, 108659)
Testing matrix shape: (7729, 108659)
Vocabulary size: 108659

In [52]:
# Titles ke duplicate hone ka check
# Clean dataset mein duplicate titles count karna
duplicate_titles = df_clean["title"].duplicated().sum()

# Total unique titles count karna
unique_titles = df_clean["title"].nunique()

# Results display karna
print("Duplicate title rows:", duplicate_titles)
print("Unique titles:", unique_titles)

Duplicate title rows: 376
Unique titles: 38268

In [53]:
# Duplicate titles inspect karna
# Duplicate titles wali rows identify karna
duplicate_title_rows = df_clean[
    df_clean["title"].duplicated(keep=False)
].sort_values("title")

# Pehli 10 matching rows ke title aur label dikhana
display(
    duplicate_title_rows[["title", "label"]].head(10)
)

                                                   title label
1488    McConnell Says He’ll Obstruct ANY Effort To H...  FAKE
1535    McConnell Says He’ll Obstruct ANY Effort To H...  FAKE
32300  'Can I get it to go?' Canada's Trudeau charms ...  REAL
18124  'Can I get it to go?' Canada's Trudeau charms ...  REAL
29752  'Fierce and formidable' Dlamini-Zuma eyes Sout...  REAL
29410  'Fierce and formidable' Dlamini-Zuma eyes Sout...  REAL
19510  'Fully committed' NATO backs new U.S. approach...  REAL
38639  'Fully committed' NATO backs new U.S. approach...  REAL
32980  'He's such a dreamer:' Skepticism dogs U.S. en...  REAL
18277  'He's such a dreamer:' Skepticism dogs U.S. en...  REAL

In [54]:
# Duplicate titles ke conflicting labels check karo
# Har title ke different labels count karna
title_label_counts = (
    df_clean.groupby("title")["label"].nunique()
)

# Sirf woh titles select karna jin ke labels different hain
conflicting_titles = title_label_counts[
    title_label_counts > 1
]

# Total conflicting titles display karna
print("Titles with conflicting labels:", len(conflicting_titles))

Titles with conflicting labels: 0

In [55]:
# Duplicate titles ke article text compare karo
# Duplicate title wali rows ko title ke hisaab se group karna
duplicate_title_groups = df_clean[
    df_clean["title"].duplicated(keep=False)
].groupby("title")

# Pehle duplicate title group ko select karna
first_title = list(duplicate_title_groups.groups.keys())[0]
first_group = duplicate_title_groups.get_group(first_title)

# Title, label aur text ke starting 200 characters dikhana
display(
    first_group[["title", "label", "text"]]
    .assign(text_preview=lambda x: x["text"].str[:200])
    [["title", "label", "text_preview"]]
)

,title,label,text_preview
1488,McConnell Says He’ll Obstruct ANY Effort To H...,FAKE,Siding with Trump s Attorney General Jeff Sess...
1535,McConnell Says He’ll Obstruct ANY Effort To H...,FAKE,Siding with Trump s Attorney General Jeff Sess...

In [56]:
# Complete article text compare karo
# Dono articles ka complete text lena
text_1 = first_group["text"].iloc[0]
text_2 = first_group["text"].iloc[1]

# Complete text compare karna
print("Complete text identical:", text_1 == text_2)

# Dono texts ke characters count karna
print("First article characters:", len(text_1))
print("Second article characters:", len(text_2))

Complete text identical: False
First article characters: 2957
Second article characters: 2937

In [57]:
# Text ka farq identify karo
# Dono articles ko character-by-character compare karna
for i, (char_1, char_2) in enumerate(zip(text_1, text_2)):
    if char_1 != char_2:
        print("First difference position:", i)
        print("Article 1:", repr(text_1[max(0, i-50):i+100]))
        print("Article 2:", repr(text_2[max(0, i-50):i+100]))
        break

First difference position: 2913
Article 1: 'ustice will be his masterpiece.Featured image via Aaron P. Bernstei /Stringer via Getty Images'
Article 2: 'ustice will be his masterpiece.Featured image via Win McNamee/Getty Images'

In [58]:
# Similarity percentage check karna
from difflib import SequenceMatcher

# Dono articles ki similarity calculate karna
similarity = SequenceMatcher(
    None,
    text_1,
    text_2
).ratio()

# Percentage mein result dikhana
print("Text similarity:", round(similarity * 100, 2), "%")

Text similarity: 99.29 %

In [59]:
# Check karo ke yeh dono rows kis set mein hain
# Dono articles ke original DataFrame indices
article_indices = first_group.index.tolist()

print("Article indices:", article_indices)

Article indices: [1488, 1535]

In [60]:
# Train/test membership check
# Check karna ke dono articles training set mein hain ya nahi
for idx in article_indices:
    in_train = idx in X_train.index
    in_test = idx in X_test.index

    print(f"Index {idx}: Training={in_train}, Testing={in_test}")

Index 1488: Training=True, Testing=False
Index 1535: Training=True, Testing=False

In [61]:
# imp check
# Tamam duplicate-title rows ke indices lena
duplicate_indices = duplicate_title_rows.index

# Check karna ke har duplicate title ka koi article test set mein hai
duplicate_titles_in_test = duplicate_title_rows[
    duplicate_title_rows.index.isin(X_test.index)
]

# Result display karna
print("Duplicate-title rows in test set:", len(duplicate_titles_in_test))

Duplicate-title rows in test set: 148

In [62]:
# Duplicate titles ka cross-set overlap check
# Training set ke titles nikalna
train_titles = set(df_clean.loc[X_train.index, "title"])

# Testing set ke titles nikalna
test_titles = set(df_clean.loc[X_test.index, "title"])

# Dono sets mein common titles dhoondhna
common_titles = train_titles.intersection(test_titles)

print("Unique titles in training:", len(train_titles))
print("Unique titles in testing:", len(test_titles))
print("Titles present in both sets:", len(common_titles))

Unique titles in training: 30674
Unique titles in testing: 7712
Titles present in both sets: 118

In [63]:
# Common titles ke labels compare
# Common titles wali tamam rows select karna
common_title_rows = df_clean[
    df_clean["title"].isin(common_titles)
]

# Har title ke labels count karna
common_title_label_counts = (
    common_title_rows.groupby("title")["label"].nunique()
)

# Different labels wale titles select karna
conflicting_common_titles = common_title_label_counts[
    common_title_label_counts > 1
]

print(
    "Common titles with conflicting labels:",
    len(conflicting_common_titles)
)

Common titles with conflicting labels: 0

In [64]:
# Common titles ke articles training aur testing mein compare
# Training aur testing data mein titles ke saath text select karna
train_title_text = df_clean.loc[X_train.index, ["title", "text"]]
test_title_text = df_clean.loc[X_test.index, ["title", "text"]]

# Sirf common titles ke articles select karna
train_common = train_title_text[
    train_title_text["title"].isin(common_titles)
]
test_common = test_title_text[
    test_title_text["title"].isin(common_titles)
]

# Har common title ke training aur testing articles count karna
print("Training articles with common titles:", len(train_common))
print("Testing articles with common titles:", len(test_common))

Training articles with common titles: 143
Testing articles with common titles: 122

In [65]:
# Exact text overlap check
# Training articles ke unique text ka set banana
train_text_set = set(X_train)

# Testing articles ke unique text ka set banana
test_text_set = set(X_test)

# Dono sets mein bilkul same text dhoondhna
exact_text_overlap = train_text_set.intersection(test_text_set)

print("Exact text overlap across train/test:", len(exact_text_overlap))

Exact text overlap across train/test: 0

In [66]:
# Common titles ke articles ka text compare
# Training aur testing mein common title select karna
example_title = common_titles.pop()

# Is title ke training articles nikalna
train_examples = train_common[
    train_common["title"] == example_title
]

# Is title ke testing articles nikalna
test_examples = test_common[
    test_common["title"] == example_title
]

print("Selected title:", example_title)
print("Training articles:", len(train_examples))
print("Testing articles:", len(test_examples))

Selected title: Waiting for May, Brussels eyes December Brexit deal
Training articles: 1
Testing articles: 1

In [67]:
# Text similarity calculate
from difflib import SequenceMatcher

# Training article ka text lena
train_text = train_examples["text"].iloc[0]

# Testing article ka text lena
test_text = test_examples["text"].iloc[0]

# Dono articles ki similarity calculate karna
similarity = SequenceMatcher(
    None,
    train_text,
    test_text
).ratio()

print("Training text length:", len(train_text))
print("Testing text length:", len(test_text))
print("Text similarity:", round(similarity * 100, 2), "%")

Training text length: 4444
Testing text length: 4833
Text similarity: 80.24 %

In [68]:
# Dono articles ka starting text compare
# Training article ke pehle 500 characters
print("TRAINING ARTICLE:")
print(train_text[:500])

# Testing article ke pehle 500 characters
print("\nTESTING ARTICLE:")
print(test_text[:500])

TRAINING ARTICLE:
BRUSSELS (Reuters) - When Theresa May visits Brussels on Friday, EU negotiators will be listening intently for signs the British prime minister is preparing to risk a domestic backlash and raise her offer to secure a Brexit deal in December. European Union officials and diplomats from the other 27 member states involved in the process hope that within a week to 10 days of meeting European Council President Donald Tusk, during a summit with ex-Soviet neighbors, May will deliver movement on three

TESTING ARTICLE:
BRUSSELS (Reuters) - When Theresa May visits Brussels on Friday, EU negotiators will be listening intently for signs the British prime minister is preparing to risk a domestic backlash and raise her offer to secure a Brexit deal in December. European Union officials and diplomats from the other 27 member states involved in the process hope that within a week to 10 days of meeting European Council President Donald Tusk, during a summit with ex-Soviet neighbors, May will deliver movement on three

In [69]:
# Dono articles ke labels aur full-text difference check
# Training article ka label nikalna
train_label = df_clean.loc[train_examples.index[0], "label"]

# Testing article ka label nikalna
test_label = df_clean.loc[test_examples.index[0], "label"]

# Labels aur text lengths display karna
print("Training label:", train_label)
print("Testing label:", test_label)
print("Labels match:", train_label == test_label)

print("Training text length:", len(train_text))
print("Testing text length:", len(test_text))
print("Full texts identical:", train_text == test_text)

Training label: REAL
Testing label: REAL
Labels match: True
Training text length: 4444
Testing text length: 4833
Full texts identical: False

In [70]:
# Check karo ke common title kitne characters tak same hai
# Dono texts mein pehla difference kahan aata hai, yeh dhoondhna
common_prefix_length = 0

for char_1, char_2 in zip(train_text, test_text):
    if char_1 != char_2:
        break
    common_prefix_length += 1

print("Exact matching characters from start:", common_prefix_length)
print(
    "Percentage of training text matched from start:",
    round(common_prefix_length / len(train_text) * 100, 2),
    "%"
)
print(
    "Percentage of testing text matched from start:",
    round(common_prefix_length / len(test_text) * 100, 2),
    "%"
)

Exact matching characters from start: 844
Percentage of training text matched from start: 18.99 %
Percentage of testing text matched from start: 17.46 %

In [71]:
# Near-duplicate audit ko systematic banana
# Common titles ke training aur testing articles ke starting 500 characters
train_common_prefixes = set(
    train_common["text"].str[:500]
)

test_common_prefixes = set(
    test_common["text"].str[:500]
)

# Dono sets mein common starting text
common_prefixes = train_common_prefixes.intersection(
    test_common_prefixes
)

print("Unique training prefixes:", len(train_common_prefixes))
print("Unique testing prefixes:", len(test_common_prefixes))
print("Matching 500-character prefixes:", len(common_prefixes))

Unique training prefixes: 142
Unique testing prefixes: 122
Matching 500-character prefixes: 16

In [72]:
# matching prefixes
# Dono sets mein matching prefixes ko list mein convert karo
matching_prefix_list = list(common_prefixes)

# Pehle 3 matching prefixes print karo
for i, prefix in enumerate(matching_prefix_list[:3], start=1):
    print(f"\n--- Matching Prefix {i} ---")
    print(prefix)

--- Matching Prefix 1 ---
VATICAN CITY (Reuters) - Callista Gingrich, wife of the former speaker of the U.S. House of Representatives, on Friday became U.S. ambassador to the Vatican, which is at odds with Washington over immigration, climate change and Jerusalem. Callista Gingrich, 51, an author, documentary filmmaker and former congressional aide, presented her credentials to Pope Francis at the Vatican to officially assume her role. Her husband Newt Gingrich was an early supporter and vocal ally of U.S. President Dona

--- Matching Prefix 2 ---
Global health officials are racing to better understand the Zika virus behind a major outbreak that began in Brazil last year and has spread to many countries in the Americas.  The following are some questions and answers about the virus and current outbreak: How do people become infected? Zika is transmitted to people through the bite of infected female mosquitoes, primarily the Aedes aegypti mosquito, the same type that spreads dengue, chikungunya and yellow fever. The Pan American Health Orga

--- Matching Prefix 3 ---
BRUSSELS (Reuters) - When Theresa May visits Brussels on Friday, EU negotiators will be listening intently for signs the British prime minister is preparing to risk a domestic backlash and raise her offer to secure a Brexit deal in December. European Union officials and diplomats from the other 27 member states involved in the process hope that within a week to 10 days of meeting European Council President Donald Tusk, during a summit with ex-Soviet neighbors, May will deliver movement on three

In [73]:
# Matching prefix kis split mein hai
for i, prefix in enumerate(matching_prefix_list[:3], start=1):
    print(f"\n--- Prefix {i} ---")

    train_matches = train_common[
        train_common["text"].str.startswith(prefix)
    ]

    test_matches = test_common[
        test_common["text"].str.startswith(prefix)
    ]

    print("Training matches:", len(train_matches))
    print("Testing matches:", len(test_matches))

    print("\nTraining titles:")
    print(train_matches["title"].tolist())

    print("\nTesting titles:")
    print(test_matches["title"].tolist())

--- Prefix 1 ---
Training matches: 1
Testing matches: 1

Training titles:
["Callista Gingrich becomes Trump's envoy to pope as differences mount"]

Testing titles:
["Callista Gingrich becomes Trump's envoy to pope as differences mount"]

--- Prefix 2 ---
Training matches: 1
Testing matches: 1

Training titles:
['Factbox: Why the Zika virus is causing alarm']

Testing titles:
['Factbox: Why the Zika virus is causing alarm']

--- Prefix 3 ---
Training matches: 1
Testing matches: 1

Training titles:
['Waiting for May, Brussels eyes December Brexit deal']

Testing titles:
['Waiting for May, Brussels eyes December Brexit deal']

In [74]:
# In teen pairs ki complete text similarity check
from difflib import SequenceMatcher

for i, prefix in enumerate(matching_prefix_list[:3], start=1):
    train_row = train_common[
        train_common["text"].str.startswith(prefix)
    ].iloc[0]

    test_row = test_common[
        test_common["text"].str.startswith(prefix)
    ].iloc[0]

    similarity = SequenceMatcher(
        None,
        train_row["text"],
        test_row["text"]
    ).ratio() * 100

    print(f"\n--- Pair {i} ---")
    print("Title:", train_row["title"])
    print("Training text length:", len(train_row["text"]))
    print("Testing text length:", len(test_row["text"]))
    print(f"Full-text similarity: {similarity:.2f}%")

--- Pair 1 ---
Title: Callista Gingrich becomes Trump's envoy to pope as differences mount
Training text length: 2039
Testing text length: 2039
Full-text similarity: 99.12%

--- Pair 2 ---
Title: Factbox: Why the Zika virus is causing alarm
Training text length: 6155
Testing text length: 6899
Full-text similarity: 84.76%

--- Pair 3 ---
Title: Waiting for May, Brussels eyes December Brexit deal
Training text length: 4444
Testing text length: 4833
Full-text similarity: 80.24%

In [75]:
# Title-based split ka concept verify
# Har title kitni dafa aaya hai, yeh count karo
title_counts = df_clean["title"].value_counts()

# Woh titles select karo jo ek se zyada dafa aaye hain
repeated_titles = title_counts[title_counts > 1]

print("Total articles:", len(df_clean))
print("Unique titles:", df_clean["title"].nunique())
print("Titles repeated more than once:", len(repeated_titles))
print("Articles belonging to repeated titles:",
      repeated_titles.sum())

Total articles: 38644
Unique titles: 38268
Titles repeated more than once: 340
Articles belonging to repeated titles: 716

In [76]:
# Repeated titles ka train/test overlap
# Training aur testing ke titles alag nikalo
train_titles = set(df_clean.loc[X_train.index, "title"])
test_titles = set(df_clean.loc[X_test.index, "title"])

# Dono sets mein common titles
common_titles = train_titles.intersection(test_titles)

print("Training unique titles:", len(train_titles))
print("Testing unique titles:", len(test_titles))
print("Titles shared across train and test:", len(common_titles))

Training unique titles: 30674
Testing unique titles: 7712
Titles shared across train and test: 118

In [77]:
# Check karo ke title mein missing values hain ya nahi
# Missing titles count karo
print("Missing titles:", df_clean["title"].isna().sum())

# Empty ya sirf spaces wale titles count karo
empty_titles = (
    df_clean["title"].fillna("").str.strip().eq("")
)

print("Empty titles:", empty_titles.sum())

Missing titles: 0
Empty titles: 0

In [78]:
# Har title ko group ID
# Har unique title ko ek group number assign karo
title_groups = df_clean["title"].astype("category").cat.codes

print("Total group IDs:", title_groups.nunique())
print("Total article rows:", len(df_clean))
print("First 10 group IDs:")
print(title_groups.head(10).tolist())

Total group IDs: 38268
Total article rows: 38644
First 10 group IDs:
[1695, 1760, 5251, 6606, 4369, 4575, 2252, 6898, 2076, 7698]

In [79]:
# Group-based train/test split
from sklearn.model_selection import GroupShuffleSplit

# Title groups ki bunyaad par 80/20 split
group_splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, test_idx = next(
    group_splitter.split(
        df_clean["text"],
        df_clean["label"],
        groups=title_groups
    )
)

# Naye training aur testing datasets
X_train_group = df_clean["text"].iloc[train_idx]
X_test_group = df_clean["text"].iloc[test_idx]

y_train_group = df_clean["label"].iloc[train_idx]
y_test_group = df_clean["label"].iloc[test_idx]

print("Grouped training rows:", len(X_train_group))
print("Grouped testing rows:", len(X_test_group))

Grouped training rows: 30909
Grouped testing rows: 7735

In [80]:
# Verify karo ke koi title dono sets mein nahi hai
# Grouped training aur testing ke unique titles
train_group_titles = set(
    df_clean["title"].iloc[train_idx]
)

test_group_titles = set(
    df_clean["title"].iloc[test_idx]
)

# Dono sets mein common titles
shared_group_titles = train_group_titles.intersection(
    test_group_titles
)

print("Training unique titles:", len(train_group_titles))
print("Testing unique titles:", len(test_group_titles))
print("Shared titles:", len(shared_group_titles))

Training unique titles: 30614
Testing unique titles: 7654
Shared titles: 0

In [81]:
# Naye split par TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# Naya TF-IDF vectorizer
tfidf_group = TfidfVectorizer(
    stop_words="english",
    max_df=0.7
)

# Sirf grouped training data se vocabulary seekho
X_train_group_tfidf = tfidf_group.fit_transform(
    X_train_group
)

# Usi vocabulary se grouped testing data transform karo
X_test_group_tfidf = tfidf_group.transform(
    X_test_group
)

print("Training matrix shape:", X_train_group_tfidf.shape)
print("Testing matrix shape:", X_test_group_tfidf.shape)

Training matrix shape: (30909, 109292)
Testing matrix shape: (7735, 109292)

In [82]:
# logistic regression
from sklearn.linear_model import LogisticRegression

# Naya model banao
model_group = LogisticRegression(max_iter=1000)

# Sirf training data se model train karo
model_group.fit(X_train_group_tfidf, y_train_group)

print("Grouped model training complete!")

Grouped model training complete!

In [83]:
# Testing data par predictions aur accuracy
from sklearn.metrics import accuracy_score

# Testing data par predictions
y_pred_group = model_group.predict(X_test_group_tfidf)

# Predictions ki accuracy calculate karo
group_accuracy = accuracy_score(y_test_group, y_pred_group)

print(f"Grouped Model Accuracy: {group_accuracy * 100:.2f}%")

Grouped Model Accuracy: 98.03%

In [84]:
# Confusion matrix check karna
from sklearn.metrics import confusion_matrix

# Predictions aur actual labels compare karo
cm_group = confusion_matrix(
    y_test_group,
    y_pred_group,
    labels=["FAKE", "REAL"]
)

print(cm_group)

[[3380  109]
 [  43 4203]]

In [85]:
# Precision, recall aur F1-score
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_group,
        y_pred_group,
        labels=["FAKE", "REAL"],
        zero_division=0
    )
)

              precision    recall  f1-score   support

        FAKE       0.99      0.97      0.98      3489
        REAL       0.97      0.99      0.98      4246

    accuracy                           0.98      7735
   macro avg       0.98      0.98      0.98      7735
weighted avg       0.98      0.98      0.98      7735

In [86]:
# Audit ke liye data verify
print("Training articles:", len(X_train_group))
print("Testing articles:", len(X_test_group))

print("Training labels available:", len(y_train_group))
print("Testing labels available:", len(y_test_group))

Training articles: 30909
Testing articles: 7735
Training labels available: 30909
Testing labels available: 7735

In [87]:
# normalization
# Training aur testing text ko lowercase aur trim karo
train_text_normalized = (
    X_train_group.fillna("").str.lower().str.strip()
)

test_text_normalized = (
    X_test_group.fillna("").str.lower().str.strip()
)

print("Training texts:", len(train_text_normalized))
print("Testing texts:", len(test_text_normalized))

print(
    "Exact normalized text overlap:",
    len(
        set(train_text_normalized)
        .intersection(set(test_text_normalized))
    )
)

Training texts: 30909
Testing texts: 7735
Exact normalized text overlap: 1

In [88]:
# coomon text identification
# Training aur testing mein common normalized text nikalo
common_normalized_texts = (
    set(train_text_normalized)
    .intersection(set(test_text_normalized))
)

# Common text inspect karo
for text in common_normalized_texts:
    print("Text length:", len(text))
    print("Text preview:")
    print(text[:500])

Text length: 6
Text preview:
watch:

In [89]:
# watch: ke matching articles inspect
# Training mein matching rows dhoondo
train_watch = X_train_group[
    train_text_normalized == "watch:"
]

# Testing mein matching rows dhoondo
test_watch = X_test_group[
    test_text_normalized == "watch:"
]

print("Training matches:", len(train_watch))
print("Testing matches:", len(test_watch))

print("\nTraining rows:")
print(
    df_clean.loc[
        train_watch.index, ["title", "label", "text"]
    ].to_string(index=False)
)

print("\nTesting rows:")
print(
    df_clean.loc[
        test_watch.index, ["title", "label", "text"]
    ].to_string(index=False)
)

Training matches: 1
Testing matches: 1

Training rows:
                                                                                                                     title label    text
TRUMP’S BRILLIANT Director Of Communications OMAROSA Absolutely DESTROYS Joy Behar On The View…And It’s HILARIOUS! [VIDEO]  FAKE Watch:

Testing rows:
                                                                                                                        title label   text
ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 2016 Election Gets 8 Years…Lawyers Call Sentence “Harsh”…Blame Trump…LOL! [VIDEO]  FAKE Watch:

In [90]:
# Check karo ke kitne articles mein meaningful text nahi hai
# Har article ke text ki length calculate karo
text_lengths = df_clean["text"].str.strip().str.len()

# 20 ya us se kam characters wale texts count karo
short_text_mask = text_lengths <= 20

print("Texts with 20 characters or fewer:", short_text_mask.sum())

# Aise texts ke examples aur unke labels dekho
print(
    df_clean.loc[short_text_mask, ["title", "label", "text"]]
    .head(10)
    .to_string(index=False)
)

Texts with 20 characters or fewer: 26
                                                                                                                                                                                                         title label                text
                                                                                                                                                  MY FAVORITE EXCUSES…Featuring Hillary Rotten Clinton [VIDEO]  FAKE              Enjoy:
                                                                                                                                 HYSTERICAL! HERE’S WHY TRUMP SAID TO REPORTER: “I’m president and you’re not”  FAKE        Read more:WT
                                                                                                                  HOMELAND SECURITY Catering to Illegals? Three Squares Provided to Detainees on Taxpayer Dime  FAKE      Read more: TMZ
                                                                                 ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 2016 Election Gets 8 Years…Lawyers Call Sentence “Harsh”…Blame Trump…LOL! [VIDEO]  FAKE              Watch:
                                                                                    TRUMP’S BRILLIANT Director Of Communications OMAROSA Absolutely DESTROYS Joy Behar On The View…And It’s HILARIOUS! [VIDEO]  FAKE             Watch:
                                                                                                       WATCH! Anti-Trump Hag Gets Kicked Off Flight After Threatening TRUMP Supporter…Passengers Clap! [Video]  FAKE Via: GATEWAY PUNDIT
                                                                                                                           BREAKING: PRESIDENT TRUMP Signs Most Important Executive Order “To Ease The Burden”  FAKE            Via: NPR
                                                                                                                       DELUSIONAL DEMOCRATS Get A Reality Check: “No, Russia Didn’t Hack Our Election” [Video]  FAKE          Via: MRCTV
                                                                          PELOSI Lied About “Affordable” Healthcare And Now Threatens Republican “Cowards” For Ditching It: “You break it, you own it” [Video]  FAKE             Via: WT
OUCH! Paul Joseph Watson DESTROYS MTV’s Racist Propaganda Video: “Beyonce Cares So Much About ‘Black Issues’ That She Dyes Her Hair Blonde And Bleaches Her Skin To Try And Look As White As Possible” [VIDEO]  FAKE              Enjoy

In [91]:
# Short texts ki class distribution check
# Short-text rows ka label count
print(
    df_clean.loc[short_text_mask, "label"]
    .value_counts()
)

# Har label ka percentage
print(
    df_clean.loc[short_text_mask, "label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

label
FAKE    26
Name: count, dtype: int64
label
FAKE    100.0
Name: proportion, dtype: float64

In [92]:
# Short-text rows ka detailed audit
# 26 short-text rows ko alag table mein dekho
short_text_audit = df_clean.loc[
    short_text_mask,
    ["title", "label", "text"]
].copy()

# Har row ka text length bhi add karo
short_text_audit["text_length"] = (
    short_text_audit["text"].str.strip().str.len()
)

# Text length ke hisaab se sort karo
short_text_audit = short_text_audit.sort_values(
    "text_length"
)

print(short_text_audit.to_string(index=False))

                                                                                                                                                                                                         title label                 text  text_length
                                                                                                              DEAR DEMOCRATS AND LIBERALS…Stop Complaining About The Election…You’re The Ones Who Created “Us”  FAKE                Ouch!            5
OUCH! Paul Joseph Watson DESTROYS MTV’s Racist Propaganda Video: “Beyonce Cares So Much About ‘Black Issues’ That She Dyes Her Hair Blonde And Bleaches Her Skin To Try And Look As White As Possible” [VIDEO]  FAKE               Enjoy             5
                                                                                                                                                  MY FAVORITE EXCUSES…Featuring Hillary Rotten Clinton [VIDEO]  FAKE               Enjoy:            6
                                                                                 ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 2016 Election Gets 8 Years…Lawyers Call Sentence “Harsh”…Blame Trump…LOL! [VIDEO]  FAKE               Watch:            6
                                                                                    TRUMP’S BRILLIANT Director Of Communications OMAROSA Absolutely DESTROYS Joy Behar On The View…And It’s HILARIOUS! [VIDEO]  FAKE              Watch:             6
                                                                          PELOSI Lied About “Affordable” Healthcare And Now Threatens Republican “Cowards” For Ditching It: “You break it, you own it” [Video]  FAKE              Via: WT            7
                                                                                                                                              TRUMP HATER MEGYN KELLY Pummeled In Ratings While Hannity Soars!  FAKE              Via: GP            7
                                                                                                                           BREAKING: PRESIDENT TRUMP Signs Most Important Executive Order “To Ease The Burden”  FAKE             Via: NPR            8
                                                                                                           ANTI-HILLARY HALLOWEEN HOUSE Gets Violent Threats You Won’t Believe…This Woman Is So Brave! [Video]  FAKE             Via: TMZ            8
                                                                                                                                                           OOPS! WATCH THE BRILLIANT TV AD Trump Made For Cruz  FAKE           Brilliant             9
                                                                                                                                      REPORTER ASKS: Will Obama Golf Instead of Attend Scalia Funeral? [VIDEO]  FAKE          BRAVE GUY!            10
                                                                                                                       DELUSIONAL DEMOCRATS Get A Reality Check: “No, Russia Didn’t Hack Our Election” [Video]  FAKE           Via: MRCTV           10
                                                                                                                        (VIDEO) BRAVO! TV HOST SCORCHES OBAMA FOR HIS RESPONSE TO CHATTANOOGA TERRORIST ATTACK  FAKE        I VE HAD IT!            12
                                                                                                                          Anti-Trump Protesters Scream Profanities at FOX News in Segment on Peaceful Protests  FAKE       Lefty losers             12
                                                                                                                                 HYSTERICAL! HERE’S WHY TRUMP SAID TO REPORTER: “I’m president and you’re not”  FAKE         Read more:WT           12
                                                                                                                  HOMELAND SECURITY Catering to Illegals? Three Squares Provided to Detainees on Taxpayer Dime  FAKE       Read more: TMZ           14
                                                                                                                       RUSH LIMBAUGH Warns Who The GOP Will Choose If Trump Or Cruz Don’t Get Enough Delegates  FAKE       Wow! Just wow!           14
                                                                                                                    WIKILEAKS: No Stamina? Hillary’s Aide Asked To Cut Speech Due To Lack Of Podium…To Lean On  FAKE       Via: Wikileaks           14
                                                                                                                            (Video) Bill O’Reilly Donald Trump Battle Over Immigration Plan and 14th Amendment  FAKE    Spirited debate:            16
                                                                                                                                       TRUMP DOES FALLON’S TONIGHT SHOW: Talks about Hillary, Debates, Border…  FAKE    Great interview!            16
                                                                  BREAKING: UNDERCOVER VIDEO Exposes Hillary’s Dirty Operatives Inciting Violence At Trump Rallies: “We need to win this motherf*cker” [Video]  FAKE    LANGUAGE WARNING!           17
                                                                                                                               WATCH: BEST DESCRIPTION OF UK BREXIT YET…Conservatives Will Stand Up And Cheer!  FAKE   Take note America            17
                                                                                                             HAMMER TIME: TRUMP POINTS OUT THE LIES BEHIND JEB’S “Act Of Love” COMMENT IN THIS BRILLIANT VIDEO  FAKE  This ad is spot on            18
                                                                                                       WATCH! Anti-Trump Hag Gets Kicked Off Flight After Threatening TRUMP Supporter…Passengers Clap! [Video]  FAKE  Via: GATEWAY PUNDIT           19
                                                                                                          OBAMACARE LOAN SHARK: If Gov’t Can Extort More Money From TAXPAYERS…OBAMACARE Can Still Work [VIDEO]  FAKE THIS IS OUTRAGEOUS!            19
                                                                                                                                                  UNREAL! THIS ONE PHOTO SUMS UP The Anti-Trump Liberal Wackos  FAKE Great parenting huh?           20

In [93]:
# Check karo ke short texts training aur testing mein kitne hain
# Har row ka original index use karke split membership check karo
short_train_count = short_text_audit.index.isin(
    X_train_group.index
).sum()

short_test_count = short_text_audit.index.isin(
    X_test_group.index
).sum()

print("Short texts in training:", short_train_count)
print("Short texts in testing:", short_test_count)
print("Total short texts:", len(short_text_audit))

Short texts in training: 22
Short texts in testing: 4
Total short texts: 26

In [94]:
# Check the labels of short texts
print(short_text_audit["label"].value_counts())

# Display the shortest records
display(short_text_audit[["title", "text", "label"]].head(10))

label
FAKE    26
Name: count, dtype: int64

                                                   title        text label
12095  DEAR DEMOCRATS AND LIBERALS…Stop Complaining A...       Ouch!  FAKE
11890  OUCH! Paul Joseph Watson DESTROYS MTV’s Racist...      Enjoy   FAKE
11112  MY FAVORITE EXCUSES…Featuring Hillary Rotten C...      Enjoy:  FAKE
11580  ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 20...      Watch:  FAKE
11675  TRUMP’S BRILLIANT Director Of Communications O...     Watch:   FAKE
11845  PELOSI Lied About “Affordable” Healthcare And ...     Via: WT  FAKE
12405  TRUMP HATER MEGYN KELLY Pummeled In Ratings Wh...     Via: GP  FAKE
11718  BREAKING: PRESIDENT TRUMP Signs Most Important...    Via: NPR  FAKE
12277  ANTI-HILLARY HALLOWEEN HOUSE Gets Violent Thre...    Via: TMZ  FAKE
14247  OOPS! WATCH THE BRILLIANT TV AD Trump Made For...  Brilliant   FAKE

In [95]:
# Check karo ke short texts kitne chhote hain
# Count records by their text length
print(short_text_audit["text_length"].value_counts().sort_index())

text_length
5     2
6     3
7     2
8     2
9     1
10    2
12    3
14    3
16    2
17    2
18    1
19    2
20    1
Name: count, dtype: int64

In [96]:
# short records ki predictions par kya asar hai
# Get the short texts from the cleaned dataset
short_texts = df_clean.loc[short_text_audit.index, "text"]

# Convert short texts into TF-IDF features
short_texts_tfidf = tfidf_group.transform(short_texts)

# Predict their labels
short_predictions = model_group.predict(short_texts_tfidf)

# Compare actual labels with predicted labels
short_results = short_text_audit[["title", "text", "label"]].copy()
short_results["predicted_label"] = short_predictions

display(short_results)

,title,text,label,predicted_label
12095,DEAR DEMOCRATS AND LIBERALS…Stop Complaining A...,Ouch!,FAKE,FAKE
11890,OUCH! Paul Joseph Watson DESTROYS MTV’s Racist...,Enjoy,FAKE,FAKE
11112,MY FAVORITE EXCUSES…Featuring Hillary Rotten C...,Enjoy:,FAKE,FAKE
11580,ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 20...,Watch:,FAKE,FAKE
11675,TRUMP’S BRILLIANT Director Of Communications O...,Watch:,FAKE,FAKE
11845,PELOSI Lied About “Affordable” Healthcare And ...,Via: WT,FAKE,FAKE
12405,TRUMP HATER MEGYN KELLY Pummeled In Ratings Wh...,Via: GP,FAKE,FAKE
11718,BREAKING: PRESIDENT TRUMP Signs Most Important...,Via: NPR,FAKE,FAKE
12277,ANTI-HILLARY HALLOWEEN HOUSE Gets Violent Thre...,Via: TMZ,FAKE,FAKE
14247,OOPS! WATCH THE BRILLIANT TV AD Trump Made For...,Brilliant,FAKE,FAKE
14071,REPORTER ASKS: Will Obama Golf Instead of Atte...,BRAVE GUY!,FAKE,FAKE
11819,"DELUSIONAL DEMOCRATS Get A Reality Check: “No,...",Via: MRCTV,FAKE,FAKE
15061,(VIDEO) BRAVO! TV HOST SCORCHES OBAMA FOR HIS ...,I VE HAD IT!,FAKE,FAKE
13937,Anti-Trump Protesters Scream Profanities at FO...,Lefty losers,FAKE,FAKE
11294,HYSTERICAL! HERE’S WHY TRUMP SAID TO REPORTER:...,Read more:WT,FAKE,FAKE
11390,HOMELAND SECURITY Catering to Illegals? Three ...,Read more: TMZ,FAKE,FAKE
13885,RUSH LIMBAUGH Warns Who The GOP Will Choose If...,Wow! Just wow!,FAKE,FAKE
12388,WIKILEAKS: No Stamina? Hillary’s Aide Asked To...,Via: Wikileaks,FAKE,FAKE
14917,(Video) Bill O’Reilly Donald Trump Battle Over...,Spirited debate:,FAKE,FAKE
14823,TRUMP DOES FALLON’S TONIGHT SHOW: Talks about ...,Great interview!,FAKE,FAKE
12392,BREAKING: UNDERCOVER VIDEO Exposes Hillary’s D...,LANGUAGE WARNING!,FAKE,FAKE
13251,WATCH: BEST DESCRIPTION OF UK BREXIT YET…Conse...,Take note America,FAKE,FAKE
14864,HAMMER TIME: TRUMP POINTS OUT THE LIES BEHIND ...,This ad is spot on,FAKE,FAKE
11704,WATCH! Anti-Trump Hag Gets Kicked Off Flight A...,Via: GATEWAY PUNDIT,FAKE,FAKE
12313,OBAMACARE LOAN SHARK: If Gov’t Can Extort More...,THIS IS OUTRAGEOUS!,FAKE,FAKE
13615,UNREAL! THIS ONE PHOTO SUMS UP The Anti-Trump ...,Great parenting huh?,FAKE,FAKE

In [97]:
# Training aur testing results alag karo
# Find short texts that belong to the testing set
short_test_mask = short_text_audit.index.isin(X_test_group.index)

# Select only the short testing records
short_test_results = short_results.loc[short_test_mask]

# Display actual and predicted labels
display(short_test_results)

,title,text,label,predicted_label
11580,ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 20...,Watch:,FAKE,FAKE
12405,TRUMP HATER MEGYN KELLY Pummeled In Ratings Wh...,Via: GP,FAKE,FAKE
11718,BREAKING: PRESIDENT TRUMP Signs Most Important...,Via: NPR,FAKE,FAKE
13251,WATCH: BEST DESCRIPTION OF UK BREXIT YET…Conse...,Take note America,FAKE,FAKE

In [98]:
# Short-text records ko alag rakh kar clean dataset banao
# Create a separate copy for the experiment
df_experiment = df_clean.copy()

# Calculate the length of each text after removing outer spaces
text_lengths = df_experiment["text"].str.strip().str.len()

# Keep records whose text length is greater than 20
df_experiment = df_experiment.loc[text_lengths > 20].copy()

# Reset row indexes
df_experiment = df_experiment.reset_index(drop=True)

# Display the dataset size
print("Original clean dataset:", len(df_clean))
print("Experimental dataset:", len(df_experiment))
print("Records excluded:", len(df_clean) - len(df_experiment))

Original clean dataset: 38644
Experimental dataset: 38618
Records excluded: 26

In [99]:
# Dono datasets ki class distribution compare
# Calculate class percentages in the original dataset
original_distribution = (
    df_clean["label"].value_counts(normalize=True) * 100
)

# Calculate class percentages in the experimental dataset
experiment_distribution = (
    df_experiment["label"].value_counts(normalize=True) * 100
)

# Combine both results into one table
distribution_comparison = pd.DataFrame({
    "Original (%)": original_distribution,
    "Experimental (%)": experiment_distribution
})

display(distribution_comparison.round(2))

       Original (%)  Experimental (%)
label
REAL          54.84             54.87
FAKE          45.16             45.13

In [100]:
# Experimental dataset par naya train/test split
from sklearn.model_selection import train_test_split

# Separate input text and target labels
X_exp = df_experiment["text"]
y_exp = df_experiment["label"]

# Create new training and testing sets
X_train_exp, X_test_exp, y_train_exp, y_test_exp = train_test_split(
    X_exp,
    y_exp,
    test_size=0.2,
    random_state=42,
    stratify=y_exp
)

print("Training records:", len(X_train_exp))
print("Testing records:", len(X_test_exp))

Training records: 30894
Testing records: 7724

In [101]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a new TF-IDF vectorizer
tfidf_exp = TfidfVectorizer(
    stop_words="english",
    max_df=0.7
)

# Learn vocabulary from training text only
X_train_exp_tfidf = tfidf_exp.fit_transform(X_train_exp)

# Transform testing text using the same learned vocabulary
X_test_exp_tfidf = tfidf_exp.transform(X_test_exp)

# Display the matrix shapes
print("Training TF-IDF shape:", X_train_exp_tfidf.shape)
print("Testing TF-IDF shape:", X_test_exp_tfidf.shape)
print("Vocabulary size:", len(tfidf_exp.vocabulary_))

Training TF-IDF shape: (30894, 108662)
Testing TF-IDF shape: (7724, 108662)
Vocabulary size: 108662

In [102]:
# Experimental Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Create the model
model_exp = LogisticRegression(max_iter=1000)

# Train it using the experimental training data
model_exp.fit(X_train_exp_tfidf, y_train_exp)

# Predict labels for the testing data
y_pred_exp = model_exp.predict(X_test_exp_tfidf)

print("Experimental model training and prediction complete.")

Experimental model training and prediction complete.

In [103]:
# accuracy
from sklearn.metrics import accuracy_score

# Compare actual labels with predicted labels
accuracy_exp = accuracy_score(y_test_exp, y_pred_exp)

# Display accuracy as a percentage
print("Experimental Model Accuracy:", round(accuracy_exp * 100, 2), "%")

Experimental Model Accuracy: 98.11 %

In [104]:
# confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

# Display confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(
    y_test_exp,
    y_pred_exp,
    labels=["FAKE", "REAL"]
))

# Display precision, recall and F1-score
print("\nClassification Report:")
print(classification_report(
    y_test_exp,
    y_pred_exp,
    labels=["FAKE", "REAL"]
))

Confusion Matrix:
[[3372  114]
 [  32 4206]]

Classification Report:
              precision    recall  f1-score   support

        FAKE       0.99      0.97      0.98      3486
        REAL       0.97      0.99      0.98      4238

    accuracy                           0.98      7724
   macro avg       0.98      0.98      0.98      7724
weighted avg       0.98      0.98      0.98      7724

In [105]:
# Errors ko inspect karna
# Find FAKE articles incorrectly predicted as REAL
false_real_mask = (
    (y_test_exp == "FAKE")
    & (y_pred_exp == "REAL")
)

false_real_indices = y_test_exp.index[false_real_mask]

# Show a few misclassified examples
error_examples = df_experiment.loc[
    df_experiment.index.isin(false_real_indices),
    ["title", "text", "label"]
].copy()

display(error_examples.head(5))

,title,text,label
417,BREAKING: Under Trump’s Leadership FEMA Could...,"After Hurricane Harvey devastated Houston, Tex...",FAKE
1120,Russia Claims They May Have Killed ISIS Leade...,Russia s Defense Ministry is investigating whe...,FAKE
1679,Court Slams Down Trump’s Order Blocking Fundi...,"During the 2016 presidential campaign, Preside...",FAKE
2720,Virginia Seeks To Hold Trump In Contempt For ...,Donald Trump could end up behind bars if the s...,FAKE
6570,"Look Out, Big Oil: ‘Job Creation’ No Longer A...",While jobs in the solar energy sector account ...,FAKE

In [106]:
# Misclassified examples ki prediction aur probability dekho
# Get the TF-IDF features for the test set
# Select the same 5 incorrectly classified examples
error_positions = [
    i for i, idx in enumerate(X_test_exp.index)
    if idx in false_real_indices
][:5]

# Get their feature rows
error_features = X_test_exp_tfidf[error_positions]

# Predict classes and probabilities
error_predictions = model_exp.predict(error_features)
error_probabilities = model_exp.predict_proba(error_features)

# Display the results
error_analysis = error_examples.head(5).copy()
error_analysis["predicted_label"] = error_predictions
error_analysis["FAKE_probability"] = error_probabilities[:, list(model_exp.classes_).index("FAKE")]
error_analysis["REAL_probability"] = error_probabilities[:, list(model_exp.classes_).index("REAL")]

display(error_analysis[
    ["title", "label", "predicted_label", "FAKE_probability", "REAL_probability"]
].round(3))

,title,label,predicted_label,FAKE_probability,REAL_probability
417,BREAKING: Under Trump’s Leadership FEMA Could...,FAKE,REAL,0.487,0.513
1120,Russia Claims They May Have Killed ISIS Leade...,FAKE,REAL,0.407,0.593
1679,Court Slams Down Trump’s Order Blocking Fundi...,FAKE,REAL,0.281,0.719
2720,Virginia Seeks To Hold Trump In Contempt For ...,FAKE,REAL,0.438,0.562
6570,"Look Out, Big Oil: ‘Job Creation’ No Longer A...",FAKE,REAL,0.363,0.637

In [107]:
# Ek ghalat prediction ke important words dekho
# Select the first incorrectly classified article
first_error_text = X_test_exp.loc[false_real_indices[0]]

# Transform its text using the trained TF-IDF vectorizer
first_error_vector = tfidf_exp.transform([first_error_text])

# Get feature names and model coefficients
feature_names = tfidf_exp.get_feature_names_out()
coefficients = model_exp.coef_[0]

# Find the words present in this article
present_word_positions = first_error_vector.nonzero()[1]

# Display words with their model weights
word_weights = pd.DataFrame({
    "word": feature_names[present_word_positions],
    "tfidf_value": first_error_vector.data,
    "model_weight": coefficients[present_word_positions]
})

display(
    word_weights.sort_values("model_weight", ascending=False).head(10)
)

             word  tfidf_value  model_weight
120       reuters     0.014320     25.470946
154     wednesday     0.024671      6.560249
116    republican     0.040979      5.371823
102  presidential     0.023250      4.336114
147          told     0.018431      3.430231
157          year     0.019147      3.247139
39       election     0.022008      2.878148
87     opposition     0.032731      2.438127
93        percent     0.054844      2.334572
58          house     0.019941      2.264708

In [108]:
# FAKE ki taraf sab se zyada weight wale words dekho
# Display words with the strongest negative model weights
display(
    word_weights.sort_values(
        "model_weight", ascending=True
    ).head(10)
)

         word  tfidf_value  model_weight
60      image     0.021998     -7.919363
47   featured     0.022967     -7.810366
66       just     0.018955     -7.044106
52      getty     0.029273     -5.522394
152     watch     0.028711     -4.861937
61     images     0.028683     -4.811735
82      obama     0.022817     -3.216009
109    really     0.027907     -2.639483
115   reports     0.031836     -2.484126
153       way     0.023023     -2.146098

In [109]:
# Final model aur vectorizer save karo
from pathlib import Path
import joblib

# Create the models folder if it doesn't exist
models_dir = Path("models")
models_dir.mkdir(parents=True, exist_ok=True)

# Save the title-grouped model and its TF-IDF vectorizer
joblib.dump(model_group, models_dir / "fake_news_model.pkl")
joblib.dump(tfidf_group, models_dir / "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!

In [110]:
import joblib
from pathlib import Path

# Load the saved model and vectorizer
models_dir = Path("models")
loaded_model = joblib.load(models_dir / "fake_news_model.pkl")
loaded_tfidf = joblib.load(models_dir / "tfidf_vectorizer.pkl")

# Enter a sample news text
news_text = input("Enter news text: ")

# Convert text into TF-IDF features and predict
news_features = loaded_tfidf.transform([news_text])
prediction = loaded_model.predict(news_features)[0]

print("Predicted label:", prediction)

Enter news text:  The government announced a new education policy today to improve schools across the country.

Predicted label: FAKE